name = "applications"
description = "Access to installed applications"
caveat = "This feature provides write access to the user's applications folder"

[files]
platform.ReadOnly = ["/usr/share/applications"]
user.ReadWrite = ["$XDG_DATA_HOME/applications"]
