name = "dri"
description = "DRI for accelerated video rendering"

libraries = [
  "dri",
  "gbm",
  "libMesa*",
  "libGL*",
  "libEGL*"
]

devices = ["/dev/dri"]

[files]
platform.ro = [
  "/sys/devices/pci0000:00",
  "/sys/dev/char"
]

resources.ro = [
  "/usr/share/glvnd",
  "/usr/share/libdrm",
]
