name = "dri"
description = "DRI for accelerated video rendering"

libraries = [
  "/usr/lib/dri",
  "/usr/lib/gbm",
  "libMesa*",
  "libGL*",
  "libEGL*"
]

devices = ["/dev/dri"]

[files]
platform.ReadOnly = [
  "/sys/devices/pci0000:00",
  "/sys/dev/char"
]

resources.ReadOnly = [
  "/usr/share/glvnd",
  "/usr/share/libdrm",
]
