name = "flatpak-spawn"
description = "Use Antimony-Spawn to permit sandboxes to run other applications under Antimony."
namespaces = ["User"]

binaries = [
  "$AT_HOME/utilities/antimony-spawn=/usr/bin/flatpak-spawn",
  "ldd", "bwrap", "find", "bash"
]
