name = "fonts"
description = "Provide host fonts and config."

[files]
platform.ro = [
  "/usr/share/fonts",
  "/usr/share/fontconfig",
  "/etc/fonts"
]
user.ro = [
  "$XDG_CONFIG_HOME/fontconfig",
  "$XDG_DATA_HOME/fontconfig",
  "$XDG_DATA_HOME/fonts",
  "$HOME/.fonts",
]
