name = "glycin"
description = "Gnome Image Loading."
requires = ["gir", "flatpak-spawn"]
conflicts = ["hardened_malloc"]

files.resources.ReadOnly = [
  "/usr/include/glycin-2/",
  "/usr/include/glycin-gtk4-2/",
  "/usr/share/glycin-loaders/"
]

libraries = [
  "glycin-loaders",
  "libglycin*"
]

binaries = ["prlimit"]
