name = "gnutls"
description = "TLS for secure network communications."
requires = ["gir", "locale"]

libraries = [
  "libgnutls*",
  "/usr/lib/pkcs11"
]

[files]
platform.ReadOnly = [
  "/etc/gnutls",
  "/etc/pkcs11",
]
resources.ReadOnly = [
  "/usr/share/p11-kit/",
]
