name = "gst"
description = "GStreamer for video/audio playback"
requires = ["gir", "passwd", "python"]

libraries = [
  "gstreamer-1.0",
  "libgst*",
]

files.resources.ReadOnly = ["/usr/share/gstreamer-1.0/"]
