name = "gtksourceview"
description = "GTK Syntax Highlighting"
requires = ["gtk4"]

libraries = ["libgtksourceview*"]

[files]
resources.ReadOnly = [
  "/usr/share/gtksourceview-5/",
  "/usr/share/gtksourceview-4/",
]
