name = "hardened_malloc"
description = "Enforce Hardened Malloc as the memory allocator within the sandbox"
caveat = "Hardened Malloc can cause noticeable performance degredation."
libraries = ["libhardened_malloc.so"]

[files.direct.ReadOnly]
"/etc/ld.so.preload" = "libhardened_malloc.so"

[environment]
"LD_PRELOAD" = "libhardened_malloc.so"
