name = "locale"
description = "Provide localization information"

libraries = [
  "locale",
  "gconv",
]

[files]
platform.ro = [
  "/etc/localtime",
  "/usr/share/zoneinfo",
  "/usr/share/locale"
]

[environment]
LANG = "$LANG"
