name = "locale"
description = "Provide localization information"

libraries = [
  "/usr/lib/locale",
  "/usr/lib/gconv",
]

[files]
platform.ReadOnly = [
  "/etc/localtime",
  "/usr/share/zoneinfo",
  "/usr/share/locale"
]

[environment]
LANG = "$LANG"
