name = "network"
description = "Give applications network connectivity."

namespaces = ["Net"]

files.platform.ReadOnly = [
  "/etc/gai.conf",
  "/etc/host.conf",
  "/etc/hosts",
  "/etc/nsswitch.conf",
  "/etc/resolv.conf",
  "/etc/ca-certificates",
  "/etc/pki",
  "/etc/ssl",
]
files.resources.ReadOnly = [
  "/usr/share/ca-certificates",
  "/usr/share/pki",
  "/usr/share/ssl",
]
