name = "pipewire"
description = "The PipeWire socket for video/audio."

files.platform.ro = [
 "$XDG_RUNTIME_DIR/pipewire-0",
 "$XDG_RUNTIME_DIR/pulse",
 "/etc/pipewire",
]
files.resources.ro = [
  "/usr/share/pipewire",
]

files.user.ro = [
  "$XDG_CONFIG_HOME/pulse"
]

libraries = [
  "libpipewire*",
  "pipewire-0.3",
  "spa-0.2",
  "pulseaudio",
]
