name = "qt6"
description = "Provide necessary files for QT6 applications"

requires = ["wayland", "fonts", "themes", "mime", "dri", "locale"]

libraries = ["qt6", "libQt6*"]

[files]
user.ro = [
  "$XDG_CONFIG_HOME/kdedefaults",
  "$XDG_CONFIG_HOME/breezerc",
  "$XDG_CONFIG_HOME/kdeglobals",
  "$XDG_CONFIG_HOME/Trolltech.conf",
  "$XDG_CONFIG_HOME/kde.org"
]
resources.ro = [
  "/usr/share/qt6"
]

[environment]
"QT_QPA_PLATFORM" = "wayland"
