name = "themes"
description = "Pass host themes, cursors, and icons"

requires = ["mime"]

[files]
platform.ro = [
  "/usr/share/themes", "/usr/share/color-schemes",
  "/usr/share/icons", "/usr/share/pixmaps",
  "/usr/share/cursors"
]
user.ro = [
  "$XDG_DATA_HOME/pixmaps",
]

[ipc]
portals = ["Settings"]
