name = "udev"
description = "Device information"
caveat = "This provides access to /sys, allowing the sandbox to see all devices."

binaries = ["udevadm", "dmidecode"]

[files]
platform.ReadOnly = [
  "/etc/udev",
  "/usr/share/hwdata",
  "/sys"
]
