name = "vulkan"
description = "Vulkan libraries and configuration."

files.platform.ReadOnly = ["/etc/vulkan"]
files.resources.ReadOnly = ["/usr/share/vulkan"]
libraries = ["libvulkan*", "libVkLayer*"]
