name = "webkit"
description = "WebKit for rendering web-content"
requires = ["gir", "gio"]

libraries = [
  "webkitgtk-6.0/",
  "libjavascriptcoregtk*",
  "libwebkitgtk*",
]

[ipc]
portals = ["Realtime"]
