home.policy = "Enabled"
home.lock = true

features = ["electron", "pipewire", "vaapi", "network", "xdg-open", "qt5", "mpris"]
arguments = ["--ozone-platform=wayland"]

[ipc]
portals = ["FileChooser"]
