features = ["gdk-pixbuf", "gir", "kf6", "python", "tray"]
libraries = ["libnotify*"]

[ipc]
system_bus = true

[files.user]
rw = ["$XDG_CONFIG_HOME/firewall"]

[files.platform]
ro = ["/etc/firewall"]
