id =  "com.github.neithern.g4music"
home.policy = "Enabled"

features = ["libadwaita", "mpris", "pipewire", "gst", "vaapi"]

[files]
user.rw = ["Music"]

[ipc]
portals = ["Background", "FileChooser", "Inhibit"]
