home.policy = "Enabled"
home.lock = true

features = ["electron", "network", "shell", "xdg-open"]
arguments = ["--ozone-platform=wayland"]

[files]
platform.ReadOnly = ["/usr/share/applications/proton-mail.desktop"]
