home.policy = "Enabled"

features = ["gtk3", "python", "network", "gtksourceview"]
libraries = ["libvirt*", "libosinfo*", "libspice-client*"]

[files]
resources.ro = [
  "/usr/share/osinfo",
  "/usr/share/hwdata",
]
platform.ro = [
  "/var/run/libvirt",
  "/sys"
]

[ipc]
system_bus = true
own = ["org.virt-manager.virt-manager"]
