path = "/usr/lib/zed/zed-editor"
id =  "dev.zed.Zed"
home.policy = "Enabled"

features = ["wayland", "dri", "vulkan", "fonts", "shell"]

[files]
passthrough = "rw"

[ipc]
portals = ["Settings", "FileChooser", "Documents"]
