[package]
name = "seccomp"
version = "0.1.0"
edition = "2024"

[features]
notify = []

[dependencies]
nix = { version = "0.30.1", default-features = false }
thiserror = { version = "2.0.17", default-features = false }
