[package]
name = "notify"
version = "0.1.0"
edition = "2024"

[dependencies]
Inflector = { version = "0.11.4", default-features = false }
console = { version = "0.16.2", default-features = false, features = ["std"] }
log = "0.4.29"
spawn = { path = "../spawn"}
user = {path = "../user"}
